likecoin/app-like-co

- pages/view/_iscnId.vue
替之前有寫入 metadata.creator 的 ISCN ( 即無 metadata.authorName )，顯示 creator name
> 🐛 Fix author info bug

- components/IscnCard.vue
- components/IscnUploadedInfo.vue
- components/SearchResult.vue
- pages/embed/card/_iscnId.vue
- pages/view/_iscnId.vue
I encountered random `window is not defined` server error in test env, but cannot reliably reproduce
Just as a defensive method to lazy load iscn card components
> 🐛 Lazyload IscnCard to prevent importing p5 in server

- components/RootLayout.vue
- nuxt.config.js
Missing `hid` will cause 2 viewports in `<meta/>`
> 🐛 Fix viewport setup

- pages/view/_iscnId.vue
Page exceeds 100% of screen high and width.
https://user-images.githubusercontent.com/75730405/152785614-4361627c-30fd-44a1-a8fd-43d42483cda3.mov
fix
> 🐛 [/view/_iscnId] Fix page exceeds the screen

- pages/view/_iscnId.vue
then we can just use an iscn prefix path to get latest iscn info
> 🐛 Fix cannot display iscn id without version

- nuxt.config.js
Fixes CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
> 🔒️ Allow wasm-eval

- package.json
- pages/nft/iscn/_iscnId.vue
- yarn.lock
iscn-js 0.2.0-rc version auto injects all iscn info into class, 0.2.1 removes this and reduces gas needed
A further update to iscn-js would calculate gas used according to tx size instead of hardcode
> ♻️ Update iscn-js and add url and description when minting class

- pages/nft/iscn/_iscnId.vue
Confusing error message would show up now if og image fetch has any error, e.g. CORS
> 🚑️ Ignore og image fetch error in nft mint

- pages/airdrop/check.vue
now it goes to `/airdrop/airdrop/claim`
> 🐛 Fix airdrop claim redirect path

- pages/nft/url/index.vue
- server/crawler/index.ts
- server/crawler/router.ts
it is hard to know if a string is encoded or not, but let's assume a unencoded string changes on `decode()`
> 🐛 Handle un/encoded url in crawler api

- components/EditableForm.vue
The confirm button cannot be clicked if the message byte length is exceeded.
> 🐛 Guard creator message by byte length

- components/EditableForm.vue
.once works, but one minor issue: if user keep closing and opening dialog it can repeatedly trigger
> 📈 Add creator message event

- components/SearchResults.vue
- pages/search/_keyword.vue
- pages/works/index.vue
Store pagination in qs to allow backing to same search/work page state from view page
> 🚸 Store pagination and use same window for work/search result

- components/IscnUploadedInfo.vue
- components/SearchResult.vue
- pages/embed/card/_iscnId.vue
- pages/view/_iscnId.vue
the `fetch()` was causing some issue which I am not sure why
But making `asyncData()` populating both `iscnId` and `owner` solves the issue
Also wrapping <client only> for component does not prevent server from loading it as js, thus `window is not defined` error would occur. Using v-if and mounted as a temp hack
> 🚑️ Fix view iscn page ssr outsync issue

- pages/nft/url/index.vue
- 404ing `wallet` or `liker_id` should not stop the following flow
- skip allow check in testnet env
> 🚸 Improve error handling in nft url mounted

- components/NFTMint/WriterMessage.vue
- components/TextField.vue
- components/TextFieldList.vue
- components/WalletFieldList.vue
The issue is due to adding `key` prop force `<input>` to  be blur
Turns out updating the value prop of `<input/>` doesn't update the inner value of `<input/>`
So, I have to add a watcher for `<TextField/>` `value` prop and update the `<input/>` value
> 🐛 Fix mint & reserve amount focus

- pages/nft/iscn/_iscnId.vue
Fix #380.
The update won't be triggered if the initial price setting component remains untouched.
> 🐛 Set default initial batch to 4 (128 LIKE)

- components/NFTMint/WriterMessage.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
Depends on https://github.com/likecoin/likecoin-api-public/pull/506
https://github.com/likecoin/app-like-co/assets/33746295/5e900318-6728-4ec5-b7a6-3e22bf9ae57c
> [TAS-205] ✨ Add 'Collectable Before' feature

- nuxt.config.js
- pages/view/_iscnId.vue
The error related to arweave upload are too obscure in user report, lets try just log every console.error for the time being
> 🔊 capture console.error in sentry

- components/NFTMint/WriterMessage.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
> [TAS-376]🎨 Change initial price to USD

- components/Link.vue
setting `href = null/undefined` would unwantedly overwrite `NuxtLink`'s href
> 🔍️ Do no overwrite href in NuxtLink with null

- components/IscnRegisterForm.vue
- components/IscnUploadForm.vue
- components/Previewer.vue
- constant/index.ts
- locales/en.json
- pages/new/index.vue
- pages/nft/url/index.vue
- utils/cosmos/iscn/index.ts
- utils/cosmos/iscn/iscn.type.ts
- utils/cosmos/iscn/sign.ts
> [TAS-553] ✨ Support uploading multiple files

- components/IscnRegisterForm.vue
Should use `gas` in estimation result, which is not affected by gas price
> 🚑️ Fix gas is overestimated by 9 digit

- components/IscnRegisterForm.vue
- components/Selector.vue
> [TAS-798] ✨ Add more license options

- components/IscnRegisterForm.vue
Since registering ISCN is now split into two steps, there's no need to set a 5s timeout for the re-open bug anymore.
so the retry button will no longer be affected by the reset of `isOpenKeplr`.
> [TAS-800] 🎨 Remove the retry action when opening Keplr

- locales/en.json
- pages/search/_keyword.vue
- pages/view/_iscnId/index.vue
- utils/cosmos/index.ts
ISCN is not preminted
ISCN is preminted
Search for owner
> [TAS-889] Add related link to likerland 

- components/IscnRegisterForm.vue
- locales/en.json
- types/author.d.ts
> [TAS-918] 🚸 Add iscnOwner to stakeholders

- constant/index.ts
- pages/edit/_iscnId.vue
- utils/cosmos/iscn/sign.ts
Even though the multiplier has been used and iscn-js updated, the wanted gas fee for updating ISCN is still slightly insufficient.
Therefore, I increased the multiplier from 1.5 to 1.75
> [TAS-954] 🩹 Increase gas multiplier for updating ISCN

- components/IscnEditBar.vue
- components/IscnUploadedInfo.vue
- pages/view/_iscnId/index.vue
> [TAS-1062]💄 Add ISCN edit bar to the /new page

- components/IscnRegisterForm.vue
> [TAS-1217] 🚸 Add default value to stakeholders

- components/IscnRegisterForm.vue
- components/SameAsFieldList.vue
- locales/en.json
- pages/edit/_iscnId.vue
- Update field order
- Update sameAs List UI
- Consolidate some settings into the `other settings` section
**sameAs section**
**other settings - book**
**other settings - not book**
> [TAS-1096]🚸 Revamp field order & UI for ISCN registration

- components/IscnUploadForm.vue
> [TAS-1297] 🚸 Add signing progress for multi-file upload

- components/IscnRegisterForm.vue
- components/IscnUploadForm.vue
When a user uploads a PDF and a JPG/PNG image simultaneously, the first uploaded image should be set as the default cover image and written into the ISCN's thumbnail field.
QA flow:
1. Navigate to /new to register an ISCN.
2. Upload a PDF and an image.
3. Complete the registration process.
4. Verify in the downloaded JSON file if the thumbnail field has been populated.
> [TAS-1216] ✨ Define book cover for PDF file

- components/IscnRegisterForm.vue
- locales/en.json
> [TAS-2030] 💄 Add inLanguage field for book

- components/AppHeader.vue
- layouts/wallet.vue
- pages/auth/redirect.vue
- store/wallet.ts
- utils/auth.ts
Action only takes one parameter
> 🐛 Fix JWT permissions not signed

- components/ContentFingerprintLink.vue
- components/IscnRegisterForm.vue
- components/IscnUploadForm.vue
- components/SameAsFieldList.vue
- constant/api.ts
- locales/en.json
- pages/new/index.vue
- pages/nft/iscn/_iscnId.vue
- pages/view/_iscnId/index.vue
- utils/arweave/v2.ts
Base on https://github.com/likecoin/app-like-co/pull/494
> [TAS-1968] ✨ Add Arweave link DRM option

- nuxt.config.js
authcore requires `document.referrer` exists in iframe to work
referrer policy cannot be `no-referrer`
> 🔧 Fix authcore referrer issue
