- nuxt.config.js
ERR_STORE_NOT_PROVIDED error otherwise
> 💩 Disable i18n vuex support due to conflict with decorator

- components/IscnRegisterForm.vue
- components/IscnUploadedInfo.vue
- components/Link.vue
- components/SearchResult.vue
- components/SearchResults.vue
- components/Stepper.vue
- components/UploadForm.vue
- pages/view/_iscnId.vue
- pages/works/index.vue
> ♻️ Refactor tag & Remove placeholder

- components/Button.vue
- components/IscnRegisterForm.vue
Fix disable behavior issue from [here](https://www.notion.so/likecoin/db890d07b1484dc3bd7f45bcfdc8f08e)
> 🐛 Fix disable behavior

- components/Card.vue
- components/Dialog.vue
- components/InfoCard.vue
- components/IscnRegisterForm.vue
- components/MetadataCard.vue
- components/UploadForm.vue
- pages/view/_iscnId.vue
1. Apply Card component to MetaDataCard
2. Modify modal layout with position & overflow settings
3. Fix image preview size
4. Modify the width of cards on the view page
> ♻️ Modify Card's Layout

- components/IscnRegisterForm.vue
Temp UI for 2 step sign dialog just to demo the logic, feel free to remove or rewrite anything
> 💩 Temp UI for sign dialog

- components/Button.vue
Hover
Active
Also fixed label height not match root
> 💄 [Button] Improve outlined preset in light bg

- components/IscnRegisterForm.vue
- components/IscnUploadForm.vue
- components/Snackbar.vue
- locales/en.json
- server/arweave/index.ts
1. Add a warning to prevent users from uploading files exceeding 20 MB.
2. Update the UI of submitting to arweave.
3. Add the timeout config.
> 🐛 Fix timeout issue on large file uploads

- components/Dialog.vue
- components/IscnRegisterForm.vue
- locales/en.json
- pages/new/index.vue
1. Improved the cancellation behavior for both author editing and signing.
2. Implemented a new signing UI.
[task here](https://www.notion.so/likecoin/Implement-new-signing-UI-d36eb9eac04b4822918916909b99b3bc)
> ♻️ Improve the cancellation behavior

- server/arweave/index.ts
stub arweaveId should not be overwritten by original key in object destruction
Use ipfs hash as stub since it is sensitive to file change
> 🐛 Fix buggy manifest generation

- pages/view/_iscnId.vue
e.g. https://mainnet-node.like.co/iscn/records/id?iscn_id=iscn://likecoin-chain/reHbsF71cuEgtjK8oahB59cDKhjoTu6NclCTddTzoI8/1
> 🥅 Guard stakeholder without entity

- server/arweave/index.ts
- server/arweave/router.ts
- server/config/config.js
- server/ipfs/index.ts
Allow making copy to our internal ipfs server
> ✨ Add multi ipfs server support

- components/SubscriptionCard.vue
@nwingt Seems main and airdrop branch are not current, not sure which branch to pr to
> 📈 Add airdrop subscription event

- components/SubscriptionCard.vue
Add simple generalized function
> 📈 Add more airdrop social subscription event

- components/IscnFormHeader.vue
- components/IscnUploadedInfo.vue
- components/Page.vue
- components/RootLayout.vue
- layouts/popup.vue
- locales/en.json
- pages/new/index.vue
- pages/view/_iscnId.vue
Path `/view/:iscnId?layout=popup`
The layout is done, need to fine-tune the responsive elements
> ✨ [view/_iscnId] Add popup layout

- server/arweave/index.ts
arql is deprecated, we should use faster gql endpoint
> ⚡️ Improve performance by switching to arweave gql

- components/AirdropDashboard.vue
- components/AirdropProgress.vue
- pages/airdrop/claim.vue
Only show if no error message and no wallet address
> Separate error & without wallet conditions

- components/AirdropMissionDialog.vue
- components/Dialog.vue
- locales/en.json
1. Add a footer slot to Dialog
2. Move buttons to ` #footer ` 
3. Congratulation -> Congratulations
> 💩 [Dialog] Add footer to fasten buttons

- pages/airdrop/claim.vue
The delay issue has been fixed, so I redirect the tx URL to Bigdipper.
> 🎨 Use bigdipper url instead of raw tx

- pages/view/_iscnId.vue
Should not block whole page waiting for txhash, it is not an crucial information
> ⚡️ Do not block page waiting for txHash

- pages/view/_iscnId.vue
> 💄 Update popup layout with add raw data

- components/IscnUploadedInfo.vue
- components/ProgressIndicator.vue
- pages/view/_iscnId.vue
https://user-images.githubusercontent.com/75730405/160523425-5d69cb47-9e54-44aa-a862-78febeb04746.mov
> 💄 Add progress indicator for txhash field

- components/IscnCard.vue
- components/MetadataCard.vue
- pages/view/_iscnId.vue
- correct the version by fetching data from records data instead of metadata
- show file preview as long as the content type is image
- add progress indicator for loading preview image
> 💄 UI improvement in [View/details] page

- pages/works/index.vue
> 🚸 Sort ISCN by latest content

- components/Button.vue
- components/IscnUploadForm.vue
- components/RootLayout.vue
- constant/index.ts
- locales/en.json
- pages/airdrop/claim.vue
> 💄 [/RootLayout] Add blocking message for chain upgrade

- components/StakeholderInfo.vue
- pages/view/_iscnId.vue
- utils/cosmos/iscn/sign.ts
should be `did:like:(address)` instead of `did:like:like(address)`
> 🐛 Fix like address id was not parsed properly

- nuxt.config.js
Only works in mobile and desktop PWA
> 💄 Add theme color in header

- constant/api.ts
- package.json
- pages/nft/iscn/_iscnId.vue
- yarn.lock
Related: https://github.com/likecoin/likecoin/pull/9
> ✨ Add proper uri, image and metadata when minting nft

- pages/nft/url/index.vue
Allow user to mint nft via url or iscn id in same screen
> ✨ Allow entering iscn id in url screen

- components/StakeholderInfo.vue
- constant/index.ts
- package.json
- utils/cosmos/iscn/sign.ts
- yarn.lock
✨ Update stakeholders @id no use did
> ✨ Update stakeholders @id no use did

- pages/nft/purchase/_iscnId.vue
- Guard insufficient balance
- Display error response message from server side
> 🥅 [nft/purchase] Guard insufficient balance

- pages/index.vue
- pages/search/_keyword.vue
- store/iscn.ts
- tsconfig.json
> ✨ Support querying by keyword

- pages/nft/purchase/_iscnId.vue
> ✨ Add user ts in purchase

- server/crawler/index.ts
✨ Add origin img src in crawler
> ✨ Add origin img src in crawler

- store/iscn.ts
+ replace search function to call indexer instead of lcd
- concern: tx is not included in indexer search all api
> :zap: Replace search to indexer

- pages/search/_keyword.vue
- store/iscn.ts
Should be `keywords` instead of `keyword`
> 🐛 Fix wrong qs for keywords query

- constant/index.ts
- utils/ipfs.ts
> 🐛 Fix constant index for ipfs

- pages/nft/url/index.vue
- server/config/config.js
> ✨ Check arweave api error

- server/crawler/index.ts
- server/utils/index.ts
🐛 Fix file name no slash for arweave
> 🐛 Fix file name no slash for arweave

- server/crawler/index.ts
> ♻️ Fix no ./

- pages/nft/iscn/_iscnId.vue
- pages/nft/url/index.vue
- server/crawler/index.ts
- server/crawler/router.ts
- `console.error(error)` and throw user-friendly `ERROR_MESSAGE` when catching an error in child functions.
- `setError(ERROR_MESSAGE)` when catching an error in functions that bonded with UI components. 
- Control ISCN registration flow with state pattern.
> ✨ Support retrying & skipping features for ISCN registration and format error handling structure

- pages/nft/url/index.vue
- server/crawler/index.ts
> ✨ Add crawler ogImage

- pages/nft/url/index.vue
📈 Add url mint NFT logTrackerEvent
> 📈 Add url mint NFT logTrackerEvent 

- store/wallet.ts
♻️ Remove throw error in initIfNecessary
> ♻️ Remove throw error in initIfNecessary

- pages/nft/iscn/_iscnId.vue
> 📈 Add mint NFT logTracker

- pages/nft/iscn/_iscnId.vue
> 🔊 Add mint nft error log

- components/StakeholderInfo.vue
- package.json
- yarn.lock
> ⬆️ Upgrade iscn.js 0.3.0

- server/crawler/index.ts
> ♻️ Add check encode

- components/IscnInfoCard.vue
Improve landing page load performance
> ⚡️ Lazy load frontend image

- server/ipfs/index.ts
should not upload to web3storage if onlyHash is set
> 🚑️ Respect onlyHash in ipfs functions

- server/crawler/index.ts
♻️ Fix ogImage logic according to firebase
> ♻️ Fix ogImage logic according to firebase

- pages/view/_iscnId.vue
> 💄 Move bottom mint NFT button into popup layout window

- components/IscnInfoCard.vue
- components/NFTMint/Process.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
- pages/nft/url/index.vue
> 🚸 <NFTMintProcess> Block minting with Wallet Connect

- nuxt.config.js
- utils/cosmos/index.ts
- utils/cosmos/iscn/query.ts
- utils/cosmos/iscn/sign.ts
- utils/cosmos/sign.ts
> ⚡️ Lazy load cosmjs libs and simplify bn.js to prevent large js bundle

- constant/index.ts
- locales/en.json
- pages/nft/url/index.vue
Block the action button if the input URL / iscnId is invalid.
> 🥅 Guard invalid input value

- pages/nft/iscn/_iscnId.vue
- pages/nft/url/index.vue
- pages/view/_iscnId.vue
> ✨ Support passing custom NFT prefix via qs

- layouts/wallet.vue
- pages/view/_iscnId.vue
Depends on https://github.com/likecoin/app-like-co/pull/282 since qs is passed from there
> 💄 Hide wallet footer if popup qs is defined

- pages/view/_iscnId.vue
> ♻️ Refactor stakeholder displayname and info parsing

- components/NFTMint/Preview.vue
- pages/nft/iscn/_iscnId.vue
Allow user to directly replace image blob and upload the blob to arweave for display
> ✨ Add upload custom image

- components/Button.vue
- components/NFTMint/Preview.vue
> 💄 [Portal] Update upload cover button

- pages/view/_iscnId.vue
> 💄 Align mint NFT button in details

- locales/en.json
- pages/view/_iscnId.vue
> ✨ Add view content button in iscn view page

- components/InfoCard.vue
- pages/view/_iscnId.vue
> 💄 Restructure details page layout

- pages/nft/iscn/_iscnId.vue
Last time the limit we test is 40, but no idea how to test on rinkeby first before release though
> ✨ Allow app to mint 35 wnft

- pages/nft/iscn/_iscnId.vue
https://github.com/likecoin/likecoin-api-public/pull/427
> 👽️ Support `platform` qs in mint API

- components/NFTMint/Preview.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
> ✨ Allow editing NFT name and description

- components/IscnUploadedInfo.vue
- pages/view/_iscnId.vue
I dont understand how store action in asyncData only cause issue under popup layout
but seems not fetching solves the issue
> 💩 Mitigate SSR issue on view popup

- components/IscnCard.vue
- components/IscnUploadedInfo.vue
- components/SearchResult.vue
- pages/embed/card/_iscnId.vue
- pages/view/_iscnId.vue
For some reason, using client-only as the root of iscn-card solves many hydration issue
> 🎨 Simplify IscnCard client only logic

- pages/nft/iscn/_iscnId.vue
seems error message is never set
> 🚸 Show error message in ui

- components/NFTMint/Process.vue
- constant/api.ts
- locales/en.json
- nuxt.config.js
- pages/nft/iscn/_iscnId.vue
> ✨ Add 3d model on mint complete

- components/NFTMint/Preview.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
- pages/nft/url/index.vue
- Input type error (no changed):
- Sign failed/ network error (add link to DC):
- Warning block for no URL in metadata (remove snack bar):
> 🚸 Improve error handling during NFT minting process

- constant/index.ts
- pages/view/_iscnId.vue
> 🚸 Display usageInfo based on input type

- package.json
- pages/nft/iscn/_iscnId.vue
- yarn.lock
Pre-calculate class id when creating class + royalty config
next step might be merging create class, royalty config, mint and send into 1 tx
> ⚡️ Merge new nft class and create royalty tx

- pages/nft/iscn/_iscnId.vue
reduce default number of nft minted to 256/32
merge create,mint,send tx if not on app
merge create,mint tx if on app
> ⚡️ Merge class create & mint/send NFT tx when not size limited

- pages/nft/iscn/_iscnId.vue
- pages/nft/url/index.vue
- server/crawler/index.ts
Upload og image in iscn registration and pass the arweave id to next page
Removes send LIKE tx for arweave in nft page if arweave id already exists
> ✨ Crawl OG image and pass to NFT mint page

- utils/cosmos/iscn/sign.ts
estimate iscn fee modified `contentfingerprints`, which modifies iscn payload, which triggers estimate iscn fee
> 🚑️ Fix contentFingerprint infinite loop

- components/NFTMint/WriterMessage.vue
- locales/en.json
- pages/nft/iscn/_iscnId.vue
> [TAS-152] ✨ Support minting free wnft

- constant/network.ts
- package.json
- yarn.lock
> ⬆️ Upgrade @likecoin/wallet-connector to v0.25.0

- components/IscnRegisterForm.vue
- utils/logger.ts
Prevent retrying causes duplicated LIKE payment in isnc file upload state
> 🚸 Store arweave payment tx hash in local state

- components/IscnUploadedInfo.vue
- locales/en.json
- pages/view/_iscnId.vue
> [TAS-624] ✨ Support downloading iscn JSON in [/_iscnId]

- pages/view/_iscnId.vue
> [TAS-485] 💄 Wrap stakeholder tags

- components/IscnRegisterForm.vue
- components/IscnUploadForm.vue
- components/SameAsFieldList.vue
- locales/en.json
- pages/new/index.vue
https://github.com/likecoin/app-like-co/assets/75730405/36bfc1aa-0be7-45a5-9047-3028600b9beb
> [TAS-597] 🚚 Separate upload only mode and register ISCN

- components/icon/Copy.vue
- locales/en.json
- pages/view/_iscnId/index.vue
- utils/ui.js
> [TAS-797]💄 [/view/_iscnId] Add a copy button for IscnId

- components/IscnUploadedInfo.vue
> [TAS-797] 🚸 Enable copy iscnId on new page

- components/FormField.vue
> [TAS-567] 💄 Update text-wrap style to break-word

- pages/nft/iscn/_iscnId.vue
Reduce nft mint count can reduce gas fee, especially for first time user
> 👔 Change wnft default mint amount to 32

- layouts/default.vue
- nuxt.config.js
- package.json
- yarn.lock
Remove PWA for DX and less storage until we actually use any PWA feature
> 🔥 Remove @nuxtjs/pwa

- layouts/default.vue
Actually I am not sure if we should keep or remove `lg:hidden` here
> 🔥 Remove undefined isDesktopViewMode

- components/IscnRegisterForm.vue
https://www.notion.so/likecoin/368d153204a242d48b56083ab6caaf04?v=73202c365bc44255870ef26817a4dfa9&p=c72a697856ec4015bd7a4550c82025e3&pm=s
> [TAS-1293] 🎨 Increase character limit to name field

- components/SameAsFieldList.vue
https://www.notion.so/likecoin/368d153204a242d48b56083ab6caaf04?v=73202c365bc44255870ef26817a4dfa9&p=657be65c55994d18ae90748150c74edc&pm=s
> [TAS-1332] 🚸 Improve sameAs url editing behavior

- components/IscnRegisterForm.vue
edit -> isOpenAuthorDialog -> editDialog -> confirmAuthorChange -> if currentAuthorDialogType = author, this.author = new author
if currentAuthorDialogType = stakeholder(default), stakeholder = new author
> 🐛 Fix incorrect assignment of author name

- pages/edit/_iscnId.vue
> ✨ Support updating more ISCN fields

- components/IscnUploadForm.vue
- locales/en.json
> [TAS-2213] 🚸 Add maximum upload file size info
